name: Auto CherryPick PR

permissions: 
  pull-requests: write
  issues: write
  repository-projects: write

env:
  PR_LABEL_PREFIX_CHERRYPICK: "cherrypick-"
  CHERRYPICK_LABEL: "robot-cherrypick"
  DEFAULT_REVIEWER: "ty-dc"

on:
  push:
    branches:
      - 'release-*'
      - 'main'
  workflow_dispatch:
    inputs:
      prNumber:
        description: 'pr number'
        required: true
      destBranch:
        description: 'dest branch, if empty, follow the pr label'
        required: false

jobs:
  cherry_pick:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: echo
        id: echo
        run: |
          echo 123456 > robot.txt

      - uses: actions/create-github-app-token@v1.6.2
        id: generate_token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v5.0.2
        with:
          title: "test"
          commit-message: test
          branch: robot-test
          delete-branch: false
          base: release-v0.8
          committer: ty-dc <tao.yang@daocloud.io>
          author: ty-dc <tao.yang@daocloud.io>
          signoff: true
          token: ${{ steps.generate_token.outputs.token }}
          labels: ${{ env.CHERRYPICK_LABEL }}
          body: "this is test xxxxx"
          reviewers: ty-dc

      - name: Creat Issue
        id: create_issue
        if: ${{ env.FAIL == 'true' && env.UPDATE != 'true' }}
        uses: dacbd/create-issue-action@v1.2.1
        with:
          token: ${{ secrets.WELAN_PAT }}
          title: "failed to cherry pick PR ${{ env.PR_NUMBER }} from ${{ env.PR_AUTHOR }}, to branch ${{ env.BRANCH }}"
          body: |
            commits ${{ env.PR_COMMITS }} of ${{ env.PR_AUTHOR }} conflict when merging to branch ${{ env.BRANCH }}.
            please manually cherry pick it by yourself. 
            PR <${{ env.PR_URL }}> , action <${{ env.ACTION_URL }}> .
            error log:
            <${{ env.ERROR_MESSAGE }}>
          labels: ${{ env.CHERRYPICK_LABEL }}
          assignees: ${{ env.PR_AUTHOR }},${{ env.DEFAULT_REVIEWER }}

      - name: check result
        if: ${{ steps.create_pr.result == 'failure' || steps.create_issue.result == 'failure' }}
        run: |
              # if failed to create issue or pr, fails
              echo "error, failuire happened"
              exit 1
